name: Run Tests

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create apt cache directory
        run: |
          sudo mkdir -p /tmp/apt-cache
          sudo chmod 777 /tmp/apt-cache

      - name: Cache OS dependencies
        id: cache-os-deps
        uses: actions/cache@v3
        with:
          path: /tmp/apt-cache
          key: ${{ runner.os }}-apt-cache-${{ hashFiles('.github/apt-packages.txt') }}
          restore-keys: |
            ${{ runner.os }}-apt-cache-

      - name: Install OS dependencies
        run: |
          # Configure apt to use our cache directory
          echo "Dir::Cache::Archives /tmp/apt-cache;" | sudo tee -a /etc/apt/apt.conf.d/01cache
          sudo apt-get update
          xargs -a .github/apt-packages.txt sudo apt-get install -y --no-install-recommends

      - name: Cache Lua dependencies
        id: cache-lua-deps
        uses: actions/cache@v3
        with:
          path: ~/.luarocks # Corrected path for where --local installs
          key: ${{ runner.os }}-luarocks-${{ hashFiles('lualextras-0.7.1-1.rockspec') }}
          restore-keys: |
            ${{ runner.os }}-luarocks-

      - name: print me
        run: |
          pwd ; ls -lah
      - name: Install Lua dependencies
        if: steps.cache-lua-deps.outputs.cache-hit != 'true'
        run: |
          luarocks install --local --only-deps lual-0.7.1-1.rockspec
          luarocks install --local --only-deps lualextras-0.7.1-1.rockspec
      # Note: busted is now installed via luarocks from lualextras rockspec
      # but also available via apt as backup from .github/apt-packages.txt
      - name: Run tests
        env:
          LUAROCKS_LOCAL: true
        run: luarocks test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
         token: ${{ secrets.CODECOV_TOKEN }}