name: Run Tests

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create apt cache directory
        run: |
          sudo mkdir -p /tmp/apt-cache
          sudo chmod 777 /tmp/apt-cache

      - name: Cache OS dependencies
        id: cache-os-deps
        uses: actions/cache@v3
        with:
          path: /tmp/apt-cache
          key: ${{ runner.os }}-apt-cache-${{ hashFiles('.github/apt-packages.txt') }}
          restore-keys: |
            ${{ runner.os }}-apt-cache-

      - name: Install OS dependencies
        run: |
          # Configure apt to use our cache directory
          echo "Dir::Cache::Archives /tmp/apt-cache;" | sudo tee -a /etc/apt/apt.conf.d/01cache
          sudo apt-get update
          xargs -a .github/apt-packages.txt sudo apt-get install -y --no-install-recommends

      - name: Configure Lua environment
        run: |
          # Create luarocks config directory
          mkdir -p ~/.luarocks
          # Ensure luarocks uses lua5.4 by setting environment variables
          echo "Configuring luarocks to use lua5.4..."
          export LUA_VERSION=5.4
          export LUA=/usr/bin/lua5.4
          # Verify lua5.4 is available
          echo "Lua version:"
          lua5.4 -v
          # Show luarocks configuration
          echo "LuaRocks version and config:"
          luarocks --version
          # Add local luarocks bin to PATH
          echo "$HOME/.luarocks/bin" >> $GITHUB_PATH
          echo "LUA_VERSION=$LUA_VERSION" >> $GITHUB_ENV
          echo "LUA=/usr/bin/lua5.4" >> $GITHUB_ENV
          echo "LUA_INCDIR=/usr/include/lua5.4" >> $GITHUB_ENV

      - name: Cache Lua dependencies
        id: cache-lua-deps
        uses: actions/cache@v3
        with:
          path: ~/.luarocks # Corrected path for where --local installs
          key: ${{ runner.os }}-luarocks-${{ hashFiles('lual-0.8.29-1.rockspec') }}
          restore-keys: |
            ${{ runner.os }}-luarocks-

      - name: Install deps
        run: |
          echo "Installing dependencies with lua5.4..."
          luarocks --local --lua-version=5.4 test

      - name: Run tests
        run: |
          # Ensure we're using lua5.4 with busted
          echo "Running tests with lua5.4..."
          lua5.4 -v
          # Run busted with lua5.4
          busted -c

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
         token: ${{ secrets.CODECOV_TOKEN }}