name: Run Tests

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create apt cache directory
        run: |
          sudo mkdir -p /tmp/apt-cache
          sudo chmod 777 /tmp/apt-cache

      - name: Cache OS dependencies
        id: cache-os-deps
        uses: actions/cache@v3
        with:
          path: /tmp/apt-cache
          key: ${{ runner.os }}-apt-cache-${{ hashFiles('.github/apt-packages.txt') }}
          restore-keys: |
            ${{ runner.os }}-apt-cache-

      - name: Install OS dependencies
        run: |
          # Configure apt to use our cache directory
          echo "Dir::Cache::Archives /tmp/apt-cache;" | sudo tee -a /etc/apt/apt.conf.d/01cache
          sudo apt-get update
          xargs -a .github/apt-packages.txt sudo apt-get install -y --no-install-recommends

      - name: Get latest rockspec filename
        id: get-rockspec
        env:
          PKG_NAME: lual
        run: |
          chmod +x ./bin/lua/get-latest-spec
          ROCKSPEC_FILE=$(./bin/lua/get-latest-spec)
          echo "rockspec_file=$ROCKSPEC_FILE" >> $GITHUB_OUTPUT
          echo "Using rockspec: $ROCKSPEC_FILE"

      - name: Cache Lua dependencies
        id: cache-lua-deps
        uses: actions/cache@v3
        with:
          path: ~/.luarocks # Corrected path for where --local installs
          key: ${{ runner.os }}-luarocks-${{ hashFiles(steps.get-rockspec.outputs.rockspec_file) }}
          restore-keys: |
            ${{ runner.os }}-luarocks-

      - name: print me
        run: |
          pwd ; ls -lah
      - name: Install Lua dependencies
        if: steps.cache-lua-deps.outputs.cache-hit != 'true'
        run: |
          luarocks install --tree .luarocks --only-deps ${{ steps.get-rockspec.outputs.rockspec_file }}
      
      - name: Set Lua paths
        id: set-lua-paths
        run: |
          echo "Setting Lua paths..."
          eval $(luarocks path --tree .luarocks)
          echo "LUA_PATH=$LUA_PATH" >> $GITHUB_ENV
          echo "LUA_CPATH=$LUA_CPATH" >> $GITHUB_ENV
          echo "PATH=$PATH" >> $GITHUB_ENV

      # on macos, busted comes with luarocks, but not on ubuntu:
      # Busted should now be installed via apt from .github/apt-packages.txt
      - name: Run tests
        shell: bash
        env:
          LUAROCKS_LOCAL: true
        run: |
          echo "Sourcing .envrc and running tests..."
          source .envrc && busted > test_output.log || true
          cat test_output.log
          if grep -q "0 failures / 0 errors" test_output.log; then
            exit 0
          else
            exit 1
          fi
